version: '3'

services:
  rabbitmq:
    image: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: symfony
      RABBITMQ_DEFAULT_PASS: symfony
  mysql:
    image: mysql:5.7
    volumes:
      - ./temp/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: app
      MYSQL_USER: root
    ports:
      - 3365:3306
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./temp/app/logs:/var/www/html/var/logs
      - ./temp/php/logs:/var/log/php-fpm
    environment:
      XDEBUG_CONFIG: remote_host=172.16.239.1
  nginx:
    build: docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./temp/nginx/logs:/var/log/nginx
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24